#!/bin/bash -l                                                  
#PBS -l nodes=1:ppn=6                          
#PBS -q sandyq                                      
#PBS -m abe                                               
#PBS -r n                                                        
#PBS -l walltime=48:00:00                                        
#PBS -N mitgcm-prx                                             
# EVERYTHING ABOVE THIS COMMENT IS NECESSARY, SHOULD ONLY CHANGE nodes,ppn,walltime and my_job_name VALUES                       
cd $PBS_O_WORKDIR                                                
mkdir /mnt/node_scratch/paradise/mitgcm-locked
rm /mnt/node_scratch/paradise/mitgcm-locked/*
cp -a * /mnt/node_scratch/paradise/mitgcm-locked/
cd /mnt/node_scratch/paradise/mitgcm-locked/

module load intel/intel-18
module load openmpi/3.0.0-intel-18
load_netcdf_intel

mpirun -np 6 ./mitgcmuv > output.txt

cp -a * $PBS_O_WORKDIR/
rm -rf *
cd $PBS_O_WORKDIR
